http:
  routers:
    nodered-rtr:
      rule: "Host(`nodered.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: nodered
      tls:
        certResolver: le
        options: tls-opts@file
  services:
    nodered:
      loadBalancer:
        passHostHeader: true
        servers:          
          - url: "http://10.16.10.105:1880"