http:
  routers:
    homeassistant-rtr:
      rule: "Host(`ha.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: homeassistant
      tls:
        certResolver: le
        options: tls-opts@file
  services:
    homeassistant:
      loadBalancer:
        passHostHeader: true
        servers:          
          - url: "http://10.16.10.10:8123"