http:
  routers:
    switch-rtr:
      rule: "Host(`sw01.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: switch
      tls:
        certResolver: le
        options: tls-opts@file
  services:
    switch:
      loadBalancer:
        passHostHeader: true
        servers:          
          - url: "http://10.16.99.2"