http:
  routers:
    fluidd-rtr:
      rule: "Host(`3d.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: fluidd
      tls:
        certResolver: le
        options: tls-opts@file
  services:
    fluidd:
      loadBalancer:
        passHostHeader: true
        servers:          
          - url: "http://10.16.100.102:81"