http:
  routers:
    spoolman-rtr:
      rule: "Host(`spools.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: spoolman
      tls:
        certResolver: le
        options: tls-opts@file
  services:
    spoolman:
      loadBalancer:
        passHostHeader: true
        servers:          
          - url: "http://10.16.10.150:7912"